services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: always
    network_mode: host
    privileged: true
    env_file: .env
    volumes:
      - ./home-assistant:/config
    logging:
      driver: "none"

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./homebridge:/homebridge
    logging:
      driver: "none"

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - ./plex:/config
      - ./plex/transcode:/transcode
      - /mnt/plex:/data
    logging:
      driver: "none"

  scrypted:
    container_name: scrypted
    image: ghcr.io/koush/scrypted
    restart: unless-stopped
    network_mode: host
    env_file: .env
    environment:
      - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer ${SCRYPTED_TOKEN}
      - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
    volumes:
      - ./scrypted/volume:/server/volume
    logging:
      driver: "none"
    labels:
      - "com.centurylinklabs.watchtower.scope=scrypted"

  watchtower:
    container_name: scrypted-watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${SCRYPTED_TOKEN}
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_SCOPE=scrypted
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup --scope scrypted
    ports:
      - 10444:8080
    logging:
      driver: "none"
    labels:
      - "com.centurylinklabs.watchtower.scope=scrypted"
