services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Asia/Manila
    volumes:
      - ./home-assistant:/config
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Manila
    volumes:
      - ./plex:/config
      - ./plex/transcode:/transcode
      - /media/plex:/data
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
