services:
  grist:
    container_name: grist
    image: gristlabs/grist
    environment:
      - GRIST_DEFAULT_EMAIL=${GRIST_EMAIL}
      - GRIST_SESSION_SECRET=${GRIST_SECRET}
    ports:
      - "8484:8484"
    volumes:
      - ${GRIST_VOLUME}:/persist
    restart: unless-stopped