services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    env_file: .env
    network_mode: host
    volumes:
      - /mnt/home-assistant:/config
      - ./config/otel-collector/run:/etc/services.d/home-assistant/run
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    depends_on:
      - otel-collector
        
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    depends_on:
      - otel-collector

  scrypted:
    container_name: scrypted
    image: ghcr.io/koush/scrypted
    restart: unless-stopped
    env_file: .env
    environment:
      - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer ${SCRYPTED_TOKEN}
      - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update\
    network_mode: host
    volumes:
      - /mnt/scrypted:/server/volume
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    labels:
      - "com.centurylinklabs.watchtower.scope=scrypted"
    depends_on:
      - otel-collector

  watchtower:
    container_name: scrypted-watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${SCRYPTED_TOKEN}
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_SCOPE=scrypted
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
    ports:
      - 10444:10444
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup --scope scrypted
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    labels:
      - "com.centurylinklabs.watchtower.scope=scrypted"
    depends_on:
      - otel-collector

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    env_file: .env
    command: --config=/etc/otelcol/config.yaml
    network_mode: host
    volumes:
      - ./config/otel-collector/config.yaml:/etc/otelcol/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    profiles:
      - monitored