services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      NAME: ${SAMBA_NAME}
      USER: ${SAMBA_USER}
      PASS: ${SAMBA_PASS}
    ports:
      - 445:445
    volumes:
      - ./config/samba/smb.conf:/etc/samba/smb.conf
      - ${SAMBA_VOLUME}:/storage
    restart: always
    labels:
      - "net.achrovisual.lgtm.logging.enabled=true"
      
  qbittorrent:
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrent
    environment:
      - VPN_ENABLED=${QBITTORRENT_VPN_ENABLED}
      - VPN_PROV=${QBITORRENT_VPN_PROVIDER}
      - VPN_CLIENT=${QBITORRENT_VPN_CLIENT}
      - LAN_NETWORK=${QBITTORRENT_LAN}
      - NAME_SERVERS=${QBITORRENT_NAMESERVERS}
      - WEBUI_PORT=9000
      - PUID=1000
      - PGID=1000
    ports:
      - 9000:9000
      - 8118:8118
      - 9118:9118
      - 58946:58946
      - 58946:58946/udp
    volumes:
      - ${QBITTORRENT_DATA_VOLUME}:/data
      - ${QBITTORRENT_CONFIG_VOLUME}:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - "net.achrovisual.lgtm.logging.enabled=true"
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    # profiles:
    #   - torrent