services:
  samba:
    container_name: samba
    image: dockurr/samba
    restart: always
    environment:
      NAME: ${SAMBA_NAME}
      USER: ${SAMBA_USER}
      PASS: ${SAMBA_PASS}
    ports:
      - 445:445
    volumes:
      - ./config/samba/smb.conf:/etc/samba/smb.conf
      - ${SAMBA_VOLUME}:/storage
      
  qbittorrent:
    container_name: qbittorrent
    image: binhex/arch-qbittorrentvpn
    restart: unless-stopped
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_ENABLED=yes
      - VPN_PROV=custom
      - VPN_CLIENT=wireguard
      - LAN_NETWORK=${QBITTORRENT_LAN}
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - WEBUI_PORT=9000
      - PUID=1000
      - PGID=1000
    ports:
      - 9000:9000
      - 8118:8118
      - 9118:9118
      - 58946:58946
      - 58946:58946/udp
    volumes:
      - ${QBITTORRENT_DATA_VOLUME}:/data
      - ${QBITTORRENT_CONFIG_VOLUME}:/config
      - /etc/localtime:/etc/localtime:ro
    # profiles:
    #   - torrent