services:
  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    environment:
      - INITIAL_ADMIN_EMAIL=${NGINX_EMAIL}
      - INITIAL_ADMIN_PASSWORD=${NGINX_PASSWORD}
    network_mode: host
    volumes:
      - ${NGINX_PROXY_MANAGER_VOLUME}:/data
      - ${NGINX_PROXY_MANAGER_VOLUME}/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    labels:
      - "net.achrovisual.lgtm.logging.enabled=true"
