services:
  db-migration:
    image: infisical/infisical:latest-postgres
    pull_policy: always
    container_name: infisical-db-migration
    command: npm run migration:latest
    env_file: .env
    networks:
      - infisical
    depends_on:
      db:
        condition: service_healthy

  backend:
    image: infisical/infisical:latest-postgres
    pull_policy: always
    container_name: infisical-backend
    environment:
      - NODE_ENV=production
    env_file: .env
    ports:
      - 80:8080
    networks:
      - infisical
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      db-migration:
        condition: service_completed_successfully
    restart: unless-stopped

  redis:
    container_name: infisical-dev-redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    env_file: .env
    ports:
      - 6379:6379
    networks:
      - infisical
    volumes:
      - redis_data:/data
    restart: always

  db:
    image: postgres:14-alpine
    container_name: infisical-db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - infisical
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

networks:
  infisical: