name: Check compose file

on:
  push:
    branches: [main]
    # paths:
    #   - services/**
  pull_request:
    branches: [main]
    # paths:
    #   - services/**
  workflow_dispatch:

env:
  # Home Assistant
  HOME_ASSISTANT_VOLUME: ${{ secrets.HOME_ASSISTANT_VOLUME }}

  # Homebridge
  HOMEBRIDGE_VOLUME: ${{ secrets.HOMEBRIDGE_VOLUME }}

  # Scrypted
  SCRYPTED_TOKEN: ${{ secrets.SCRYPTED_TOKEN }}
  SCRYPTED_VOLUME: ${{ secrets.SCRYPTED_VOLUME }}

  # UpSnap
  UPSNAP_VOLUME: ${{ secrets.UPSNAP_VOLUME }}

  # Plex
  PLEX_CONFIG_VOLUME: ${{ secrets.PLEX_CONFIG_VOLUME }}
  PLEX_DATA_VOLUME: ${{ secrets.PLEX_DATA_VOLUME }}
  PLEX_TRANSCODE_VOLUME: ${{ secrets.PLEX_TRANSCODE_VOLUME }}

  # Infisical
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  DB_CONNECTION_URI: ${{ secrets.DB_CONNECTION_URI }}
  ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
  SITE_URL: ${{ secrets.SITE_URL }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  REDIS_URL: ${{ secrets.REDIS_URL }}

  # Samba
  SAMBA_USER: ${{ secrets.SAMBA_USER }}
  SAMBA_PASS: ${{ secrets.SAMBA_PASS }}
  SAMBA_VOLUME: ${{ secrets.SAMBA_VOLUME }}

jobs:
  check_syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Find Compose Files
        id: find_compose
        run: |
          files=$(find ./services -type f -name "compose.yaml" -print0 | xargs -0 jq -sR .)
          echo "::set-output name=files::$files"

      - name: Check Compose Syntax
        run: |
          set -e
          files="${{ steps.find_compose.outputs.files }}"
          if [ -z "$files" ]; then
            echo "No compose.yaml files found."
            exit 0
          fi
          echo "$files" | jq -r '.[]' | while read -r file; do
            echo "Checking syntax for $file"
            docker compose -f "$file" config --quiet
            echo "Syntax OK for $file"
          done