services:
  lgtm:
    container_name: lgtm
    image: grafana/otel-lgtm
    restart: unless-stopped
    ports:
      - 4317:4317
      - 4318:4318
    logging:
    driver: json-file
    options:
      max-size: "10mb"
      max-file: "1"