services:
  mimir:
    image: grafana/mimir:2.12.0
    container_name: mimir
    ports:
      - 9090:9090
    restart: unless-stopped
    command: --config.file=/etc/mimir.yaml
    volumes:
      - /mnt/lgtm/mimir:/tmp/mimir
      - ./config/mimir/mimir.yaml:/etc/mimir.yaml
      - ./config/mimir/alertmanager.yaml:/etc/alertmanager-fallback-config.yaml

  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - JAEGER_AGENT_HOST=otelcol
    volumes:
      - /mnt/lgtm/loki:/loki

  grafana:
    image: grafana/grafana:11.0.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - /mnt/lgtm/grafana/config:/etc/grafana
      - /mnt/lgtm/grafana/data:/var/lib/grafana
      - /mnt/lgtm/grafana/logs:/var/log/grafana
      - ./config/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - loki
      - tempo
      - mimir

  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - /mnt/lgtm/tempo:/tmp/tempo
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml

  promtail:
    image: grafana/promtail:2.9.5
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    env_file: .env
    ports:
      - 4317:4317
      - 4318:4318
      - 8888:8888
    command: --config=/etc/otelcol/config.yaml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana
    volumes:
      - ./config/otel-collector/config.yaml:/etc/otelcol/config.yaml
