services:
  lgtm:
    image: grafana/otel-lgtm
    container_name: lgtm
    ports:
      - 4317:4317
      - 4318:4318
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"